ProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index.as_view(), name='index'),
    path('search/', views.projectsearch.as_view(), name='projectsearch'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('add_task_index/<int:pk>/', views.add_task_index.as_view(), name='add_task_index'),
    # URL patterns for charts
    path('user_tasks_chart/', views.user_tasks_chart, name='user_tasks_chart'),
    path('team_tasks_category/', views.team_tasks_category, name='team_tasks_category'),
    # This will include all the login-registtration etc. URL patterns:
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls',namespace="projects")),
    path('subcontractors/', include('subcontractors.urls',namespace="subcontractors")),
    path('team/', include('team.urls',namespace="team")),
    path('reports/', include('reports.urls',namespace="reports")),
    path('api/search_autocomplete/', views.search_autocomplete, name='search_autocomplete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

subcontractors/urls.py
from django.urls import path
from subcontractors import views

app_name = 'subcontractors'
urlpatterns = [
    path('contacts/', views.contact_list.as_view(), name='contact_list'),
    path('add_jobcategory/', views.add_jobcategory.as_view(), name='add_jobcategory'),
    path('add_contact/', views.add_contact.as_view(), name='add_contact'),
    path('edit_contact/<int:pk>/', views.edit_contact.as_view(), name='edit_contact'),
    path('delete_contact/<int:pk>/', views.delete_contact.as_view(), name='delete_contact'),
]

team/urls.py
from django.urls import path
from team import views

app_name = 'team'
urlpatterns = [
    path('', views.users_list.as_view(), name='users_list'),
    path('<int:pk>/', views.user_detail.as_view(), name='user_detail'),
    path('add_task_user/<int:pk>/', views.add_task_user.as_view(), name='add_task_user'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('edit_task_user/<int:pk>/', views.edit_task_user.as_view(), name='edit_task_user'),
    path('tasks/<int:pk>/', views.task_detail.as_view(), name='task_detail'),
    path('delete_task_user/<int:pk>/', views.delete_task_user.as_view(), name='delete_task_user'),
    path('worktime_list_user/<int:pk>/', views.worktime_list_user.as_view(), name='worktime_list_user'),
    path('worktime_history_user/<int:pk>/', views.worktime_history_user.as_view(), name='worktime_history_user'),
    path('add_worktime_user/<int:pk>/', views.add_worktime_user, name='add_worktime_user'),
    path('edit_worktime_user/<int:pk>/', views.edit_worktime_user.as_view(), name='edit_worktime_user'),
    path('delete_worktime_user/<int:pk>/', views.delete_worktime_user.as_view(), name='delete_worktime_user'),
    path('user_task_history/<int:pk>/', views.user_task_history.as_view(), name='user_task_history'),
    path('team_activity/', views.team_activity.as_view(), name='team_activity'),
    path('user_hours_graph/<int:pk>/', views.user_hours_graph, name='user_hours_graph'),
    path('add_worktime_task/<int:pk>/', views.add_worktime_task, name='add_worktime_task'),
]

subcontractors/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.db import models
from django.utils import timezone
from datetime import datetime

import misaka
from django import template
from projects.models import Project

# Subcontractors MODELS.PY file
# Create your models here.

class JobCategory(models.Model):
    jobcategory_name = models.CharField(max_length=264,unique=True, verbose_name="Name")
    class Meta:
        verbose_name_plural = "Job Categories"
    def __str__(self):
        return self.jobcategory_name
    def get_absolute_url(self):
        return reverse('subcontractors:job_categories_list')

class Subcontractor(models.Model):
    subcontractor_job_category = models.ForeignKey(JobCategory,related_name='category_sucontractors',on_delete=models.CASCADE, verbose_name="Category")
    subcontractor_name = models.CharField(max_length=264,unique=True, verbose_name="Name")
    subcontractor_location = models.CharField(max_length=264,unique=False, verbose_name="Location")
    subcontractor_phone_number = models.IntegerField(null=True, blank=True, verbose_name="Phone Number")
    subcontractor_contact_person = models.CharField(blank=True, max_length=264, verbose_name="Contact")
    subcontractor_description = models.CharField(max_length=264, blank=True,unique=False, verbose_name="Comment")
    def __str__(self):
        return self.subcontractor_name

class Job(models.Model):
    job_subcontractor = models.ForeignKey(Subcontractor,related_name='subcontractor_jobs',on_delete=models.CASCADE)
    job_project = models.ForeignKey(Project,related_name='project_jobs',on_delete=models.CASCADE)
    job_category = models.ForeignKey(JobCategory,related_name='job_category_jobs',on_delete=models.CASCADE)
    job_description = models.CharField(max_length=264,unique=False)
    job_status_choices = (
        ('Requested', 'Requested by subcontractor'),
        ('Received', 'Received from subcontractor'),
        ('Approved', 'Approved')
    )
    job_status = models.CharField(max_length=10, choices = job_status_choices, blank = False, default="Requested")
    job_created_date = models.DateTimeField(auto_now=True)
    job_requested_date = models.DateTimeField(default=datetime.now, blank=True)
    job_cost = models.IntegerField(blank=True,default=0)

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.job_project, self.job_category, self.job_description)

subcontractors/forms.py
from django import forms
from django.core import validators
from subcontractors.models import *

subcontractors/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from django.utils.decorators import method_decorator
from django.core.exceptions import ObjectDoesNotExist
from bootstrap_datepicker_plus import DatePickerInput
from django.forms import BaseFormSet
from subcontractors.models import *
from subcontractors.forms import *

# Subcontractors VIEWS.PY

# Job category CRUD

class add_jobcategory(LoginRequiredMixin,generic.CreateView):
# class add_jobcategory(generic.CreateView):
    fields = ('jobcategory_name',)
    model = JobCategory
    template_name = 'subcontractors/add_jobcategory.html'

class edit_jobcategory(LoginRequiredMixin,generic.UpdateView):
# class edit_jobcategory(generic.UpdateView):
    fields = ('jobcategory_name',)
    model = JobCategory
    template_name = 'subcontractors/add_jobcategory.html'

class delete_jobcategory(LoginRequiredMixin,generic.DeleteView):
# class delete_jobcategory(generic.DeleteView):
    fields = ('jobcategory_name',)
    model = JobCategory
    template_name = 'subcontractors/add_jobcategory.html'

# Subcontractor CRUD

class add_contact(LoginRequiredMixin,generic.CreateView):
# class add_contact(generic.CreateView):
    fields = '__all__'
    model = Subcontractor
    template_name = 'subcontractors/add_contact.html'
    def get_success_url(self):
        return reverse('subcontractors:job_categories_list')

class edit_contact(LoginRequiredMixin,generic.UpdateView):
# class edit_contact(generic.UpdateView):
    fields = '__all__'
    model = Subcontractor
    template_name = 'subcontractors/edit_contact.html'
    def get_success_url(self):
        return reverse('subcontractors:job_categories_list')

class delete_contact(LoginRequiredMixin,generic.DeleteView):
# class delete_contact(generic.DeleteView):
    model = Subcontractor
    template_name = 'subcontractors/delete_contact.html'
    def get_success_url(self):
        return reverse('subcontractors:job_categories_list')

class contact_list(LoginRequiredMixin,generic.ListView):
# class contact_list(generic.ListView):
    model = Subcontractor
    template_name = 'subcontractors/contact_list.html'

subcontractors/templates/subcontractors/add_contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}


<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <h2>Add a Subcontractor</h2>
      <form method="POST" action="{% url 'subcontractors:add_contact' %}" id="subcontractorForm">
        <p style="line-height:1.6em;"></p>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-large">Add</button>
        <p style="line-height:1.6em;"></p>
        <p style="margin-left:0px; font-size:0.9em">Do you want to add a new <strong><a href="{% url 'subcontractors:add_jobcategory' %}"> Category</a></strong>?</p>
      </form>
    </div>
  </div>
</div>

{% endblock %}

subcontractors/templates/subcontractors/add_jobcategory.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}


<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <h2>Add a Job Category</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'subcontractors:add_jobcategory' %}" id="jobcategoryForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary btn-large">Add</button>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

subcontractors/templates/subcontractors/contact_list.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item">Contacts</li>
  </ol>
</nav>

<div class="row justify-content-center">
  <div class="col-12">
    <p style="line-height:1.6em;"></p>
    <h4 class="table-header">Contacts<a href="{% url 'subcontractors:add_contact' %}" class="btn btn-light btn-sm" role="button"> +</a></h4>
    {% if object_list %}
    <table style="width:100%"
      data-classes="table"
      data-toggle="table"
      data-locale="en-US"
      data-pagination="true"
      data-search="true">
      <thead>
        <tr>
          <th data-sortable="true" data-field="id">Name</th>
          <th data-sortable="true" data-field="Category">Category</th>
          <th data-field="Location">Location</th>
          <th data-field="Phone number">Phone number</th>
          <th data-field="Contact person">Contact person</th>
          <th data-field="Comment">Comment</th>
          <th class="align-middle text-center" data-field="Edit">Edit</th>
          <th class="align-middle text-center" data-field="Delete">Delete</th>
        </tr>
      </thead>
      {% for subcontractor in object_list %}
      <tr>
        <td>{{ subcontractor.subcontractor_name }}</td>
        <td>{{ subcontractor.subcontractor_job_category }}</td>
        <td>{{ subcontractor.subcontractor_location }}</td>
        <td>{{ subcontractor.subcontractor_phone_number }}</td>
        <td>{{ subcontractor.subcontractor_contact_person }}</td>
        <td>{{ subcontractor.subcontractor_description }}</td>
        <td class="align-middle text-center">
          <a href="{% url 'subcontractors:edit_contact' subcontractor.pk %}" class="btn btn-sm" role="button">
            <i class="far fa-edit"></i>
          </a>
        </td>
        <td class="align-middle text-center">
          <a href="{% url 'subcontractors:delete_contact' subcontractor.pk %}" class="btn btn-sm" role="button">
            <i class="far fa-trash-alt"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </table>

  {% else %}

  <p>No contacts have been added yet.</p>
  <a href="{% url 'subcontractors:add_jobcategory' %}" class="btn btn-light btn-sm" role="button"> Add +</a>

  {% endif %}
    </div>
  </div>
</div>

{% endblock %}
{% block scripts %}

{% endblock scripts %}

subcontractors/templates/subcontractors/delete_contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-12 col-md-8 col-lg-6">
      <h2>Delete Contact</h2>
      <p style="line-height:1.6em;"></p>
      <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <button type="submit" class="btn btn-danger btn-large">Delete</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

subcontractors/templates/subcontractors/delete_jobcategory.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}


<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <h2>Delete Job Category</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'subcontractors:delete_jobcategory' %}" id="jobcategoryForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary btn-large">Delete</button>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

subcontractors/templates/subcontractors/edit_contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}


<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <h2>Edit Contact</h2>
      <form method="POST" action="{% url 'subcontractors:edit_contact' subcontractor.pk %}" id="subcontractorForm">
        <p style="line-height:1.6em;"></p>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-large">Save</button>
        <a href="{% url 'subcontractors:delete_contact' subcontractor.pk %}" class="btn btn-danger btn-large">Delete</a>
        <p style="line-height:1.6em;"></p>
        <p style="margin-left:0px; font-size:0.9em">Do you want to add a new <strong><a href="{% url 'subcontractors:add_jobcategory' %}"> Category</a></strong>?</p>
      </form>
    </div>
  </div>
</div>

{% endblock %}

subcontractors/templates/subcontractors/edit_jobcategory.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}


<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <h2>Edit Job Category</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'subcontractors:edit_jobcategory' %}" id="jobcategoryForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary btn-large">Save</button>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>

{% endblock %}