ProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index.as_view(), name='index'),
    path('search/', views.projectsearch.as_view(), name='projectsearch'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('add_task_index/<int:pk>/', views.add_task_index.as_view(), name='add_task_index'),
    # URL patterns for charts
    path('user_tasks_chart/', views.user_tasks_chart, name='user_tasks_chart'),
    path('team_tasks_category/', views.team_tasks_category, name='team_tasks_category'),
    # This will include all the login-registtration etc. URL patterns:
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls',namespace="projects")),
    path('subcontractors/', include('subcontractors.urls',namespace="subcontractors")),
    path('team/', include('team.urls',namespace="team")),
    path('reports/', include('reports.urls',namespace="reports")),
    path('api/search_autocomplete/', views.search_autocomplete, name='search_autocomplete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup.as_view(), name='signup'),
    path('edit_user/<int:pk>/', views.edit_user.as_view(), name='edit_user'),
    path('delete_user/<int:pk>/', views.delete_user.as_view(), name='delete_user'),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'
urlpatterns = [
    path('', views.project_categories_list.as_view(), name='project_categories_list'),
    path('<int:projectcategory_number>/', views.project_category.as_view(), name='project_category'),
    path('projects/<int:pk>/', views.project_detail.as_view(), name='project_detail'),
    path('add_project/<int:pk>/', views.add_project.as_view(), name='add_project'),
    path('add_projectcategory/', views.add_project_category.as_view(), name='add_project_category'),
    path('edit_project/<int:pk>/', views.edit_project.as_view(), name='edit_project'),
    path('add_job_project/<int:pk>/', views.add_job_project.as_view(), name='add_job_project'),
    path('add_task_project/<int:pk>/', views.add_task_project.as_view(), name='add_task_project'),
    path('join_project/<int:pk>/', views.join_project.as_view(), name='join_project'),
    path('leave_project/<int:pk>/', views.leave_project.as_view(), name='leave_project'),
    path('project_task_history/<int:pk>/', views.project_task_history.as_view(), name='project_task_history'),
    path('busiest_projects/', views.busiest_projects, name='busiest_projects'),
    path('busiest_project_categories/', views.busiest_project_categories, name='busiest_project_categories'),
    path('project_hours_graph/<int:pk>/', views.project_hours_graph, name='project_hours_graph'),
    path('add_worktime_project/<int:pk>/', views.add_worktime_project, name='add_worktime_project'),
    path('add_worktime_modal/<int:pk>/', views.add_worktime_modal, name='add_worktime_modal'),
]

team/urls.py
from django.urls import path
from team import views

app_name = 'team'
urlpatterns = [
    path('', views.users_list.as_view(), name='users_list'),
    path('<int:pk>/', views.user_detail.as_view(), name='user_detail'),
    path('add_task_user/<int:pk>/', views.add_task_user.as_view(), name='add_task_user'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('edit_task_user/<int:pk>/', views.edit_task_user.as_view(), name='edit_task_user'),
    path('tasks/<int:pk>/', views.task_detail.as_view(), name='task_detail'),
    path('delete_task_user/<int:pk>/', views.delete_task_user.as_view(), name='delete_task_user'),
    path('worktime_list_user/<int:pk>/', views.worktime_list_user.as_view(), name='worktime_list_user'),
    path('worktime_history_user/<int:pk>/', views.worktime_history_user.as_view(), name='worktime_history_user'),
    path('add_worktime_user/<int:pk>/', views.add_worktime_user, name='add_worktime_user'),
    path('edit_worktime_user/<int:pk>/', views.edit_worktime_user.as_view(), name='edit_worktime_user'),
    path('delete_worktime_user/<int:pk>/', views.delete_worktime_user.as_view(), name='delete_worktime_user'),
    path('user_task_history/<int:pk>/', views.user_task_history.as_view(), name='user_task_history'),
    path('team_activity/', views.team_activity.as_view(), name='team_activity'),
    path('user_hours_graph/<int:pk>/', views.user_hours_graph, name='user_hours_graph'),
    path('add_worktime_task/<int:pk>/', views.add_worktime_task, name='add_worktime_task'),
]

team/forms.py
from django import forms
from django.core import validators
from accounts.models import User
from team.models import Comment, Task, Worktime
from bootstrap_datepicker_plus import DatePickerInput
from django.contrib.auth import get_user_model
User = get_user_model()

class AddWorktimeForm(forms.ModelForm):
    class Meta:
        model = Worktime
        fields = '__all__'
        widgets = {
            'worktime_user': forms.HiddenInput(),
            'worktime_date': DatePickerInput(format='%d/%m/%Y'),
            }

class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_task','comment_author','comment_text',)
        labels = {
            'comment_text': '',
        }
        widgets = {
            'comment_author': forms.HiddenInput(),
            'comment_task': forms.HiddenInput(),
            'comment_text': forms.Textarea(),
            }

team/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.utils import timezone
from bootstrap_datepicker_plus import DatePickerInput
from django.views import generic, View
from django.http import HttpResponseForbidden
from django.views.generic.edit import FormMixin, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import FormView
from braces.views import SelectRelatedMixin
from projects.models import Project
from team.models import Task, Comment, Worktime
from team.forms import CommentForm, AddWorktimeForm
from accounts.forms import *
from django.contrib.auth import get_user_model
from django.db.models.functions import Extract
from django.db.models import Sum, Count
from django.forms.widgets import TextInput, HiddenInput, TimeInput
from django.forms import modelformset_factory, formset_factory
from django.http import JsonResponse
import datetime
User = get_user_model()

# Team VIEWS.PY
# Create your views here.


class users_list(generic.ListView):
    queryset = User.objects.all()
    template_name = 'team/user_list.html'

class user_detail(LoginRequiredMixin,generic.DetailView):
# class user_detail(generic.DetailView):
    template_name = 'team/user_detail.html'
    model = User
    context_object_name = 'user_examined'
    def get_success_url(self):
        return reverse('team:user_detail', kwargs={'pk': self.request.user.pk})
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pending_tasks = False
        context["projects_user"] = Project.objects.filter(project_members__id__icontains=self.kwargs['pk'])
        context["user_examined"] = User.objects.get(id=self.kwargs['pk'])
        context["logged_user"] = self.request.user
        # Task context
        user_tasks = Task.objects.filter(task_asignee__id=self.kwargs['pk'])
        context["tasks_all"] = user_tasks
        for task in user_tasks:
            if task.task_status == 'Pending':
                pending_tasks = True
        context["pending_tasks"] = pending_tasks
        try:
            context["completed"] = Task.objects.filter(task_owner__id=self.kwargs['pk']).filter(task_status='Completed').count() / Task.objects.filter(task_owner__id=self.kwargs['pk']).count() * 100
            context["is_due"] = Task.objects.filter(task_owner__id=self.kwargs['pk']).filter(task_status='Pending').count() / Task.objects.filter(task_owner__id=self.kwargs['pk']).count() * 100
            context["tasks"] = Task.objects.filter(task_owner__id=self.kwargs['pk'])
        except:
            context["completed"] = 0
            context["is_due"] = 0
            context["tasks"] = 0
        # Worktime context
        today = datetime.date.today()
        start_of_week_day = today - datetime.timedelta(today.weekday())
        day_difference = datetime.timedelta(days=7)
        mid_date = start_of_week_day + day_difference
        end_date = mid_date + day_difference
        both_dates = [[mid_date, end_date], [start_of_week_day, mid_date]]
        first_week = Worktime.objects.filter(worktime_date__gte=start_of_week_day,
            worktime_date__lt=mid_date).annotate(week=Extract('worktime_date',
            lookup_name='week')).filter(worktime_user__id=self.kwargs['pk'])
        second_week = Worktime.objects.filter(worktime_date__gte=mid_date,
            worktime_date__lt=end_date).annotate(week=Extract('worktime_date',
            lookup_name='week')).filter(worktime_user__id=self.kwargs['pk'])
        both_weeks = [second_week, first_week]
        hours_annotated = Worktime.objects.filter(
            worktime_user__id=self.kwargs['pk'])\
            .filter(worktime_date__gt=start_of_week_day)\
            .annotate(week=Extract('worktime_date',lookup_name='week'))\
            .annotate(year=Extract('worktime_date',lookup_name='year'))\
            .annotate(week_day=Extract('worktime_date',lookup_name='week_day'))
        context['start_date'] = start_of_week_day
        context['mid_date'] = mid_date
        context['end_date'] = end_date
        context['both_weeks'] = zip(both_weeks,both_dates)
        this_year = datetime.datetime.now().year
        context['first_week'] = first_week
        context['hours_annotated'] = hours_annotated
        context["workhours_all"] = Worktime.objects.filter(worktime_user__id=self.kwargs['pk'])\
            .annotate(week=Extract('worktime_date', lookup_name='week'))
        return context

# Task CRUD (user-specific)

class add_task_user(LoginRequiredMixin,generic.CreateView):
# class add_task_user(generic.CreateView):
    model = Task
    fields = ('task_project','task_description',
        'task_owner','task_asignee','task_due_date')
    def get_initial(self):
        return { 'task_owner': self.kwargs['pk'] }
    def get_form(self):
        form = super().get_form()
        form.fields['task_owner'].widget = HiddenInput()
        form.fields['task_due_date'].widget = DatePickerInput(format='%d/%m/%Y')
        return form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = User.objects.get(id=self.kwargs['pk'])
        return context
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    template_name = 'team/add_task_user.html'
    def get_success_url(self):
        return reverse('team:user_detail', kwargs={'pk':self.kwargs['pk']})

class edit_task_user(LoginRequiredMixin,generic.UpdateView):
# class edit_task_user(generic.UpdateView):
    model = Task
    fields = ('task_project','task_description',
        'task_asignee','task_status','task_due_date')
    def get_form(self):
        form = super().get_form()
        form.fields['task_due_date'].widget = DatePickerInput(format='%d/%m/%Y')
        return form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = User.objects.get(id=self.object.task_asignee.pk)
        return context
    template_name = 'team/edit_task_user.html'
    def get_success_url(self):
        return reverse('team:user_detail', kwargs={'pk':self.object.task_asignee.pk})

class delete_task_user(LoginRequiredMixin,generic.DeleteView):
# class delete_task_user(generic.DeleteView):
    model = Task
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = User.objects.get(id=self.object.task_asignee.pk)
        return context
    template_name = 'team/delete_task_user.html'
    def get_success_url(self):
        return reverse('team:user_detail', kwargs={'pk':self.object.task_asignee.pk})

# Comment CRUD

class AddCommentForm(SingleObjectMixin, FormView):
    template_name = 'team/task_detail.html'
    form_class = CommentForm
    model = Task
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('team:task_detail', kwargs={'pk': self.object.pk})

# class CommentForm(forms.Form):
#     template_name = 'team/task_detail.html'
#     form_class = CommentForm

class task_display(generic.DetailView):
    model = Task
    def get_success_url(self):
        return reverse('team:task_detail', kwargs={'pk': self.object.pk})
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = Task.objects.get(id=self.kwargs['pk'])
        hours_spent = Worktime.objects.filter(worktime_task=task).aggregate(Sum('worktime_hour'))
        context["form"] = CommentForm(
            initial={
            'comment_author': self.request.user,
            'comment_task': task,
            }
        )
        context["hours_spent"] = hours_spent
        context["task_comments"] = Comment.objects.filter(comment_task__id=self.kwargs['pk'])
        return context
    template_name = 'team/task_detail.html'

class task_detail(View):
    def get(self, request, *args, **kwargs):
        view = task_display.as_view()
        return view(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        view = AddCommentForm.as_view()
        return view(request, *args, **kwargs)

class edit_comment(LoginRequiredMixin,generic.UpdateView):
# class edit_comment(generic.UpdateView):
    model = Comment
    fields = ('comment_text',)
    template_name = 'team/edit_comment.html'
    def get_success_url(self):
        return reverse('team:task_detail', kwargs={'pk':self.kwargs['pk']})

class delete_comment(LoginRequiredMixin,generic.DeleteView):
# class delete_comment(generic.DeleteView):
    model = Comment
    template_name = 'team/delete_comment.html'
    def get_success_url(self):
        return reverse('team:task_detail', kwargs={'pk':self.kwargs['pk']})

# End of comments CRUD

def update_task_status(request,pk):
    task = Task.objects.get(pk=pk)
    if task.task_status == 'Pending':
        task.task_status = 'Completed'
        task.save()
    else:
        task.task_status = 'Pending'
        task.save()
    return redirect('team:user_detail', pk=task.task_owner.pk)

# Worktime CRUD

def add_worktime_user(request, pk):
    AddWorktimeFormSet = formset_factory(
        form=AddWorktimeForm,
        extra=0,
        )
    data = request.POST or None
    user_id = pk
    if request.method == 'POST':
        formset = AddWorktimeFormSet(request.POST)
        for form in formset:
            if form.is_valid() and form.has_changed():
                form.save()
            else:
                form_errors = formset.errors

team/templates/team/add_task_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-12 col-md-8 col-lg-6">
      <h2>Add a Task</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'team:add_task_user' user.id %}" id="taskForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-large">Add</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

team/templates/team/edit_task_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-12 col-md-8 col-lg-6">
      <h2>Edit Task</h2>
      <form method="POST" action="{% url 'team:edit_task_user' task.pk %}" id="taskForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary btn-large">Save</button>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

team/templates/team/edit_worktime_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-12 col-md-8 col-lg-6">
      <h2>Edit Worktime</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'team:edit_worktime_user' worktime.pk %}" id="taskForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-large">Save</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

team/templates/team/task_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'projects:project_category' task.task_project.project_category.pk %}">{{ task.task_project.project_category }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'projects:project_detail' task.task_project.pk %}">{{ task.task_project.project_name }}</a></li>
      <li class="breadcrumb-item">Tasks</li>
    </ol>
  </nav>

  <div class="row justify-content-center align-items-start">
    <div class="col-auto p-1">
      <div class="card task-card">
        <div class="chart-container">
          <h3 class="white card-description">{{ task.task_description }}
            <a href="{% url 'team:edit_task_user' task.pk %}">
              <i class="far fa-edit" style="color:white; font-size:10px">
              </i>
            </a>
          </h3>
          <table style="width:100%" class="table-sm table-hover">
            <tr class="white">
              <td class="table-label align-top">Task project:</td>
              <td class="align-top">{{ task.task_project }}</td>
            </tr>
            <tr class="white">
              <td class="table-label align-top">Assigned to:</td>
              <td class="align-top">{{ task.task_asignee }}</td>
            </tr>
            <tr class="white">
              <td class="table-label align-top">Status:</td>
              <td class="align-top">{{ task.task_status }}</td>
            </tr>
            <tr class="white">
              <td class="table-label align-top">Date created:</td>
              <td class="align-top">{{ task.task_creation_date|date:'N j, Y' }}</td>
            </tr>
            <tr class="white">
              <td class="table-label align-top">Delivery date:</td>
              <td class="align-top">{{ task.task_due_date }}</td>
            </tr>
            {% if task.task_completion_date %}
            <tr class="white">
              <td class="table-label">Date completed:</td>
              <td class="align-middle">{{ task.task_completion_date|date:'N j, Y' }}</td>
            </tr>
            {% endif %}
          </table>
        </div>
      </div>
    </div>

    <div class="col-auto mb-2 p-1">
      <div class="card user-hours">
        <div class="chart-container text-center">
          <h6 class="hours-title white">Hours logged</h6>
          {% if hours_spent.worktime_hour__sum %}
          <h1 class="hours-number white">{{ hours_spent.worktime_hour__sum }}</h1>
          {% else %}
          <h1 class="hours-number white">0</h1>
          {% endif %}
          <div class="mb-0">
            <a href="{% url 'team:add_worktime_task' task.pk %}" class="btn btn-info btn-sm">Add worktime</a>
          </div>

        </div>
      </div>
    </div>
  </div>
<br>
<br>
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <h5>Task comments</h5>
      <br>
      <form id="comment_form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button id="comment_button" type="submit" style="float: right;" class="btn-sm btn-outline-dark">Add comment</button>
      </form>
      <br>
    </div>
    {% if task_comments %}
    {% for c in task_comments %}
    <div class="comment col-12 col-md-10 col-lg-8 pt-4">
      <a href="{% url 'team:user_detail' c.comment_author.pk %}">
        <div class="circle" style="background-color:rgba{{ c.comment_author.profile.user_color }};">
          <span class="black initials" style="cursor:default">
            {{ c.comment_author.username|first|title }}
          </span>
        </div>
        <span style='margin-left:.6em;'>{{ c.comment_author }}</span>
      </a>
      <div class="ml-1 mt-3">
        <p>{{ c.comment_text }}</p>
      </div>
      <div class="row float-right mr-2">
        <p style="color:grey; font-size:11px">{{ c.comment_created_date }}</p>
      </div>
    </div>
    {% endfor %}
    {% endif %}
    </div>

  </div>

</div>
{% endblock %}

{% block scripts %}

{% endblock scripts %}

team/templates/team/user_list.html
{% extends 'base.html' %}

{% block body %}
{% load bootstrap4 %}
{% bootstrap_javascript jquery='full' %}

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item">Users</li>
    </ol>
  </nav>

  <div class="row justify-content-center">
    <div class="col-12 m-2 pl-4 pr-4">
      {% if user_list %}
      <table style="width:100%" class="table table-hover table-sm">
        <thead>
          <tr>
            <th class="align-middle" scope="col">Username</th>
            <th class="align-middle" scope="col">First name</th>
            <th class="align-middle" scope="col">Last name</th>
            <th class="align-middle" scope="col">Email</th>
            <th class="align-middle text-center" scope="col">Projects</th>
          </tr>
        </thead>
        {% for u in user_list %}
        <tr class='clickable-row' data-href="{% url 'team:user_detail' u.pk %}" >
          <td class="align-middle">{{ u.username }}</td>
          <td class="align-middle">{{ u.first_name }}</td>
          <td class="align-middle">{{ u.last_name }}</td>
          <td class="align-middle">{{ u.email }}</td>
          <td class="align-middle text-center">{{ u.user_member_projects.count }}</td>
        </tr>
        {% endfor %}
      </table>
      <a href="{% url 'accounts:signup' %}" class="btn btn-light btn-sm" role="button">Add user +</a>

      {% else %}

      <p>No users have been added yet. You first need to define</p>
      <a href="{% url 'accounts:signup' %}" class="btn btn-light btn-sm" role="button">Add user +</a>
      {% endif %}

    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function($) {
      $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
      });
    });
  </script>

{% endblock scripts %}

team/templates/team/worktime_history_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

{% bootstrap_javascript jquery='full' %}


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'team:users_list' %}">Users</a></li>
  </ol>
</nav>

<div class="container">
<br>
<h4>Worktime history for {{ user_examined }} <span style="font-size:0.9rem;"><a href="{% url 'team:add_worktime_user' user.pk %}">+</a></span></h4>
  {% if object_list %}
    <table style="width:100%"
      data-classes="table"
      data-toggle="table"
      data-locale="en-US"
      data-pagination="true"
      data-search="true">
      <thead>
        <tr>
          <th data-sortable="true" data-field="project">Project</th>
          <th data-sortable="true" data-field="task">Task</th>
          <th data-sortable="true" data-field="date" class="align-middle text-center">Date</th>
          <th class="align-middle text-center" data-field="hours">Hours</th>
          <th class="align-middle text-center" data-field="edit" >Edit</th>
          <th class="align-middle text-center" data-field="delete" >Delete</th>
        </tr>
      </thead>
        {% for workhour in object_list %}
        <tr>
          <td class="align-middle">{{ workhour.worktime_task.task_project }}</td>
          <td class="align-middle">{{ workhour.worktime_task.task_description }}</td>
          <td class="align-middle text-center" style="width:120px">{{ workhour.worktime_date|date:"d/m/Y" }}</td>
          <td class="align-middle text-center">{{ workhour.worktime_hour }}</td>
          <td class="align-middle text-center">
            <a href="{% url 'team:edit_worktime_user' workhour.pk %}" class="btn btn-sm" role="button"><i class="far fa-edit"></i></a>
          </td>
          <td class="align-middle text-center">
            <a href="{% url 'team:delete_worktime_user' workhour.pk %}" class="btn btn-sm">
              <i class="far fa-trash-alt"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
  </table>

    <p><a href="{% url 'team:add_worktime_user' user.pk %}">Add +</a></p>
{% else %}
    <p>No workhours have been added yet. You can add some
    <a href="{% url 'team:add_worktime_user' user.pk %}">here</a>
    </p>
{% endif %}

</div>

{% endblock %}

team/templates/team/worktime_list_user.html
{% if both_weeks %}
{% for week, dates in both_weeks %}
  {% if week %}
    <table style="width:100%" class="table table-hover table-sm">
      <h7>{{ dates.0|date:"D d M Y" }} - {{ dates.1|date:"D d M Y" }}</h7>
      <thead>
        <tr>
          <th class="align-middle" scope="col">Project</th>
          <th class="align-middle" scope="col">Task</th>
          <th class="align-middle text-center" scope="col">Date</th>
          <th class="align-middle text-center" scope="col">Hours</th>
          <th class="align-middle text-center" scope="col">User</th>
          <th class="align-middle text-center" scope="col">Edit</th>
          <th class="align-middle text-center" scope="col">Delete</th>
        </tr>
      </thead>
        {% for workhour in week %}
        <tr>
          <td class="align-middle">
            <a href="{% url 'projects:project_detail' workhour.worktime_task.task_project.pk %}">
            {{ workhour.worktime_task.task_project }}
            </a>
          </td>
          <td class="align-middle">{{ workhour.worktime_task.task_description }}</td>
          <td class="align-middle text-center" style="width:120px">{{ workhour.worktime_date|date:"d/m/Y" }}</td>
          <td class="align-middle text-center">{{ workhour.worktime_hour }}</td>
          <td class="align-middle text-center">{{ workhour.worktime_user }}</td>
          <td class="align-middle text-center">
            <a href="{% url 'team:edit_worktime_user' workhour.pk %}" class="btn btn-sm" role="button"><i class="far fa-edit"></i></a>
          </td>
          <td class="align-middle text-center">
            <a href="{% url 'team:delete_worktime_user' workhour.pk %}" class="btn btn-sm">
              <i class="far fa-trash-alt"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    {% endif %}
  {% endfor %}
  </table>
<p style="color:grey; font-size:12px">See {{ user_examined }}'s <a href="{% url 'team:worktime_history_user' user_examined.pk %}">worktime history</a></p>
{% else %}
    <p>No workhours have been added yet. You can add some
    <a href="{% url 'team:add_worktime_user' user.pk %}">here</a>.
    </p>
{% endif %}