ProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index.as_view(), name='index'),
    path('search/', views.projectsearch.as_view(), name='projectsearch'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('add_task_index/<int:pk>/', views.add_task_index.as_view(), name='add_task_index'),
    # URL patterns for charts
    path('user_tasks_chart/', views.user_tasks_chart, name='user_tasks_chart'),
    path('team_tasks_category/', views.team_tasks_category, name='team_tasks_category'),
    # This will include all the login-registtration etc. URL patterns:
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls',namespace="projects")),
    path('subcontractors/', include('subcontractors.urls',namespace="subcontractors")),
    path('team/', include('team.urls',namespace="team")),
    path('reports/', include('reports.urls',namespace="reports")),
    path('api/search_autocomplete/', views.search_autocomplete, name='search_autocomplete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'
urlpatterns = [
    path('', views.project_categories_list.as_view(), name='project_categories_list'),
    path('<int:projectcategory_number>/', views.project_category.as_view(), name='project_category'),
    path('projects/<int:pk>/', views.project_detail.as_view(), name='project_detail'),
    path('add_project/<int:pk>/', views.add_project.as_view(), name='add_project'),
    path('add_projectcategory/', views.add_project_category.as_view(), name='add_project_category'),
    path('edit_project/<int:pk>/', views.edit_project.as_view(), name='edit_project'),
    path('add_job_project/<int:pk>/', views.add_job_project.as_view(), name='add_job_project'),
    path('add_task_project/<int:pk>/', views.add_task_project.as_view(), name='add_task_project'),
    path('join_project/<int:pk>/', views.join_project.as_view(), name='join_project'),
    path('leave_project/<int:pk>/', views.leave_project.as_view(), name='leave_project'),
    path('project_task_history/<int:pk>/', views.project_task_history.as_view(), name='project_task_history'),
    path('busiest_projects/', views.busiest_projects, name='busiest_projects'),
    path('busiest_project_categories/', views.busiest_project_categories, name='busiest_project_categories'),
    path('project_hours_graph/<int:pk>/', views.project_hours_graph, name='project_hours_graph'),
    path('add_worktime_project/<int:pk>/', views.add_worktime_project, name='add_worktime_project'),
    path('add_worktime_modal/<int:pk>/', views.add_worktime_modal, name='add_worktime_modal'),
]

team/urls.py
from django.urls import path
from team import views

app_name = 'team'
urlpatterns = [
    path('', views.users_list.as_view(), name='users_list'),
    path('<int:pk>/', views.user_detail.as_view(), name='user_detail'),
    path('add_task_user/<int:pk>/', views.add_task_user.as_view(), name='add_task_user'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('edit_task_user/<int:pk>/', views.edit_task_user.as_view(), name='edit_task_user'),
    path('tasks/<int:pk>/', views.task_detail.as_view(), name='task_detail'),
    path('delete_task_user/<int:pk>/', views.delete_task_user.as_view(), name='delete_task_user'),
    path('worktime_list_user/<int:pk>/', views.worktime_list_user.as_view(), name='worktime_list_user'),
    path('worktime_history_user/<int:pk>/', views.worktime_history_user.as_view(), name='worktime_history_user'),
    path('add_worktime_user/<int:pk>/', views.add_worktime_user, name='add_worktime_user'),
    path('edit_worktime_user/<int:pk>/', views.edit_worktime_user.as_view(), name='edit_worktime_user'),
    path('delete_worktime_user/<int:pk>/', views.delete_worktime_user.as_view(), name='delete_worktime_user'),
    path('user_task_history/<int:pk>/', views.user_task_history.as_view(), name='user_task_history'),
    path('team_activity/', views.team_activity.as_view(), name='team_activity'),
    path('user_hours_graph/<int:pk>/', views.user_hours_graph, name='user_hours_graph'),
    path('add_worktime_task/<int:pk>/', views.add_worktime_task, name='add_worktime_task'),
]

projects/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
import misaka
from django import template

# Project MODELS.PY file

User = get_user_model()
register = template.Library()

class ProjectCategory(models.Model):
    projectcategory_number = models.IntegerField(unique=True)
    projectcategory_name = models.CharField(max_length=264,unique=True)
    projectcategory_name_html = models.TextField(editable=False,default='',blank=True)
    # projectcategory_projects = models.ManyToManyField(Project, through='ProjectCategoryProject')
    def __str__(self):
        return '{0} - {1}'.format(self.projectcategory_number, self.projectcategory_name)
    def save(self,*args,**kwargs):
        self.projectcategory_name_html = misaka.html(self.projectcategory_name)
        super().save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse('projects:project_categories_list')
    class Meta:
        # verbose_name_plural = "Project Categories"
        ordering = ['projectcategory_number']
    @property
    def user_colors(self):
        return len(str(self))*40%255, 'Hi'


class Project(models.Model):
    project_category = models.ForeignKey(ProjectCategory,related_name='category_projects',on_delete=models.CASCADE)
    project_number = models.IntegerField(unique=True)
    project_name = models.CharField(max_length=264,unique=True)
    project_stage_choices = (
        ('Concept Design', 'CD - Concept Design'),
        ('Schematic Design', 'SD - Schematic Design'),
        ('Design Development', 'DD - Design Development'),
        ('Issued for Construction', 'IFC - Issued for Construction'),
        ('Closed', 'Closed'),
    )
    project_stage = models.CharField(max_length=30, choices = project_stage_choices, blank=False, default="CD")
    project_creator = models.ForeignKey(User,related_name="project_creator",on_delete=models.CASCADE)
    project_members = models.ManyToManyField(User,related_name="user_member_projects")
    project_delivery_date = models.DateField()
    project_status_choices = (
        ('On time', 'On time'),
        ('Delayed', 'Delayed'),
    )
    project_status = models.CharField(max_length=30, choices = project_status_choices, blank=False, default="On time")
    def close_project(self):
        self.project_stage = 'Closed'
        self.save()
    def __str__(self):
        return '{0} - {1}'.format(self.project_number, self.project_name)
    class Meta:
        unique_together = ('project_number','project_creator')
        ordering = ['project_number']
    def save(self,*args,**kwargs):
        self.project_name_html = misaka.html(self.project_name)
        super().save(*args,**kwargs)

projects/forms.py
from django import forms
from django.core import validators
from bootstrap_datepicker_plus import DatePickerInput
from .models import *
from django.contrib.auth.models import User



class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'project_members': forms.SelectMultiple(attrs={
                'class': 'form-control  js-multiple',
                'multiple': 'multiple',
                }),
        }

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views import generic
from django.db.models import Case, CharField, Value, When
from django.db import IntegrityError
from django.utils.decorators import method_decorator
from bootstrap_datepicker_plus import DatePickerInput
from projects.forms import ProjectForm
from team.forms import AddWorktimeForm
from django.forms import MultipleChoiceField
from projects.models import *
from team.models import Task, Worktime
from subcontractors.models import Job
from projects import *
from django.db.models import Count, Sum
from django.http import JsonResponse, HttpResponseRedirect
from django.forms.widgets import HiddenInput
from django.forms import formset_factory
import datetime
User = get_user_model()

# Projects VIEWS.PY file
# Create your views here.

class add_project_category(LoginRequiredMixin,generic.CreateView):
# class add_project_category(generic.CreateView):
    fields = ('projectcategory_number','projectcategory_name')
    model = ProjectCategory
    template_name = 'projects/add_project_category.html'

class add_project(LoginRequiredMixin,generic.CreateView):
# class add_project(generic.CreateView):
    model = Project
    form_class = ProjectForm
    def get_initial (self):
        initial = super().get_initial()
        initial['project_category'] = ProjectCategory.objects.get(projectcategory_number=self.kwargs['pk'])
        initial['project_creator'] = self.request.user
        return initial
    def get_form(self):
        form = super().get_form()
        form.fields['project_delivery_date'].widget = DatePickerInput(format='%d/%m/%Y')
        form.fields['project_creator'].widget = HiddenInput()
        form.fields['project_status'].widget = HiddenInput()
        return form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["projectcategory"] = ProjectCategory.objects.get(projectcategory_number=self.kwargs['pk'])
        return context
    template_name = 'projects/add_project.html'
    def get_success_url(self):
        return reverse('projects:project_detail', args=[self.object.pk])
        # return reverse('projects:project_detail', kwargs={'<int:pk>': self.object.pk})

class edit_project(LoginRequiredMixin,generic.UpdateView):
# class edit_project(generic.UpdateView):
    model = Project
    form_class = ProjectForm
    def get_form(self):
        form = super().get_form()
        form.fields['project_delivery_date'].widget = DatePickerInput(format='%d/%m/%Y')
        form.fields['project_creator'].widget = HiddenInput()
        form.fields['project_status'].widget = HiddenInput()
        return form
    template_name = 'projects/edit_project.html'
    def get_success_url(self):
        return reverse('projects:project_detail', args=[self.object.pk])

today = datetime.date.today()
start_of_query = today - datetime.timedelta(days=1)
queryset = Project.objects.annotate(num_worktime=Sum('project_tasks__task_time__worktime_hour')).filter(project_tasks__task_time__worktime_date__gte=start_of_query)


class project_categories_list(LoginRequiredMixin,generic.ListView):
# class project_categories_list(generic.ListView):
    model = ProjectCategory
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = datetime.date.today()
        start_of_query = today - datetime.timedelta(days=14)
        context["project_hours_2weeks"] = Project.objects.filter(project_tasks__task_time__worktime_date__gte=start_of_query)
        context["user"] = self.request.user
        return context
    template_name = 'projects/project_categories_list.html'

class project_category(generic.ListView):
    # only projects belonging to a certainn category
    model = Project
    def get_queryset(self):
        return Project.objects.filter(project_category__projectcategory_number=self.kwargs['projectcategory_number'])
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        projectcategory = ProjectCategory.objects.filter(projectcategory_number=self.kwargs['projectcategory_number'])
        context["project_category"] = ProjectCategory.objects.get(projectcategory_number=self.kwargs['projectcategory_number'])
        return context
    template_name = 'projects/project_category.html'

class project_detail(LoginRequiredMixin,generic.DetailView):
# class project_detail(generic.DetailView):
    model = Project
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        project = Project.objects.filter(id=self.kwargs['pk'])
        project_tasks = Task.objects.filter(task_project__id=self.kwargs['pk'])
        pending_tasks = False
        for task in project_tasks:
            if task.task_status == 'Pending':
                pending_tasks = True
        try:
            context["completed"] = Task.objects.filter(task_project__id=self.kwargs['pk']).filter(task_status='Completed').count() / Task.objects.filter(task_project__id=self.kwargs['pk']).count() * 100
            context["is_due"] = Task.objects.filter(task_project__id=self.kwargs['pk']).filter(task_status='Pending').count() / Task.objects.filter(task_project__id=self.kwargs['pk']).count() * 100
            context["tasks"] = Task.objects.filter(task_project__id=self.kwargs['pk'])
        except:
            context["completed"] = 0
            context["is_due"] = 0
            context["tasks"] = 0
        context['tasks_all'] = project_tasks
        context['user'] = self.request.user
        context['jobs'] = Job.objects.filter(job_project__id=self.kwargs['pk'])
        context['pending_tasks'] = pending_tasks
        context['project_tasks'] = project_tasks
        context["workhours_all"] = Worktime.objects.filter(worktime_task__task_project_id=self.kwargs['pk'])
        AddWorktimeFormSet = formset_factory(
            form=AddWorktimeForm,
            extra=0,
            )
        formset = AddWorktimeFormSet(initial=[{'worktime_user': self.request.user}])
        for form in formset:
            form.fields['worktime_task'].queryset = Task.objects.filter(task_asignee=self.request.user,\
            task_project_id=self.kwargs['pk'])
        context['formset'] = formset
        return context
    template_name = 'projects/project_detail.html'

class join_project(LoginRequiredMixin,generic.RedirectView):
# class join_project(generic.RedirectView):
    def get(self,request,*args,**kwargs):
        active_user = self.request.user
        project = get_object_or_404(Project,pk=self.kwargs.get('pk'))
        try:
            project.project_members.add(active_user.pk)
        except IntegrityError:
            messages.warning(self.request,'You have already joined this project')
        else:
            messages.success(self.request,'You have now joined this project!')
        return super().get(request,*args,**kwargs)
    def get_redirect_url(self,*args,**kwargs):
        return reverse('projects:project_detail',kwargs={'pk':self.kwargs.get('pk')})

class leave_project(LoginRequiredMixin,generic.RedirectView):
# class leave_project(generic.RedirectView):
    def get(self,request,*args,**kwargs):
        active_user = self.request.user
        project = get_object_or_404(Project,pk=self.kwargs.get('pk'))
        try:
            member = project.project_members.filter(pk=active_user.pk).get()
        except project.project_members.DoesNotExist:
            messages.warning(self.request,"You can't leave this project because you aren't in it.")
        else:
            project.project_members.remove(active_user.pk)
            messages.success(self.request,"You have successfully left this project.")
        return super().get(request,*args,**kwargs)
    def get_redirect_url(self,*args,**kwargs):
        return reverse('projects:project_detail',kwargs={'pk':self.kwargs.get('pk')})

class add_job_project(LoginRequiredMixin,generic.edit.CreateView):
# class add_job_project(generic.edit.CreateView):
    model = Job
    fields = ('job_description','job_subcontractor',
    'job_project','job_category','job_status',
    'job_requested_date','job_cost')
    def get_initial (self):
        initial = super().get_initial()
        initial['job_project'] = Project.objects.get(id=self.kwargs['pk'])
        return initial
    def get_form(self):
         form = super().get_form()
         form.fields['job_requested_date'].widget = DatePickerInput(format='%d/%m/%Y')
         return form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project"] = Project.objects.get(id=self.kwargs['pk'])
        return context
    template_name = 'projects/add_job_project.html'
    def get_success_url(self):
        return reverse('projects:project_detail', args=[self.object.job_project.pk])

# Project Task CRUD

class add_task_project(LoginRequiredMixin,generic.CreateView):
# class add_task_project(generic.CreateView):
    model = Task
    fields = ('task_project','task_description',
        'task_owner','task_asignee','task_due_date')
    def get_initial(self):
        return {
        'task_project': self.kwargs['pk'],
        'task_owner': self.request.user,
        'task_asignee': self.request.user
        }
    def get_form(self):
        form = super().get_form()
        form.fields['task_owner'].widget = HiddenInput()
        form.fields['task_due_date'].widget = DatePickerInput(format='%d/%m/%Y')
        return form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project"] = Project.objects.get(id=self.kwargs['pk'])
        return context

projects/templates/projects/add_project.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css">
<style>
.select2-search__field{
  line-height: 31px !important;
}

</style>
{{ form.media }}


<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <form method="POST" action="{% url 'projects:add_project' projectcategory.projectcategory_number %}" id="projectForm">
        <h2>Add a Project</h2>
        <p style="line-height:1.6em;"></p>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-large">Add</button>
        <p style="line-height:1.6em;"></p>
        <p style="margin-left:0px; font-size:0.9em">Do you want to add a new <strong><a href="{% url 'projects:add_project_category' %}"> Project Category</a></strong>?</p>
      </form>
    </div>
  </div>
</div>

{% endblock body %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('.js-multiple').select2();
  });

$.fn.select2.defaults.set( "theme", "bootstrap" );
</script>

{% endblock scripts %}

projects/templates/projects/add_project_category.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <form method="POST" action="{% url 'projects:add_project_category' %}" id="projectcategorysForm">
        <h2>Add a Project Category</h2>
        <p style="line-height:1.6em;"></p>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-large">Add</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

projects/templates/projects/add_task_project.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-12 col-md-8 col-lg-6">
      <h2>Add a Task</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'projects:add_task_project' project.pk %}" id="taskForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary btn-large">Add</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

projects/templates/projects/add_worktime_modal.html
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ formset.media }}

<div class="modal fade" id="addWorktimeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content col">
      <div class="modal-header">
        <h5 class="modal-title"">Add Worktime</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class="col">
              <form method="POST" action="{% url 'projects:add_worktime_modal' project.pk %}" id="worktimeForm">

                {{ formset.management_form }}
                {% csrf_token %}
                {% for form in formset %}
                <h4>Worktime</h4>
                <div class="worktime-form">
                  <br>
                  {% bootstrap_form form %}
                </div>
                {% endfor %}
                <button id="add-form" type="button" class="btn btn-outline-primary mb-4">Add another</button>
                <br>
                <p>
                  <button type="submit" class="btn btn-primary btn-large">Save</button>
                  <a href="{% url 'projects:project_detail' project.pk %}"><button type="button" class="btn btn-default btn-large">Cancel</button></a>
                </p>
                <p style="line-height:1.6em;"></p>
                <p style="margin-left:0px; font-size:0.9em">Do you want to add a new <strong><a href="{% url 'team:add_task_user' user.pk %}"> Task</a></strong>?</p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
let worktimeForm = document.querySelectorAll(".worktime-form")
let container = document.querySelector("#worktimeForm")
let addButton = document.querySelector("#add-form")
let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

let formNum = worktimeForm.length-1
addButton.addEventListener('click', addForm)

function addForm(e){
    e.preventDefault()

    let newForm = worktimeForm[0].cloneNode(true)
    let formRegex = RegExp(`form-(\\d){1}-`,'g')

    formNum++
    newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
    container.insertBefore(newForm, addButton)

    totalForms.setAttribute('value', `${formNum+1}`)
}

</script>
{% endblock scripts %}

projects/templates/projects/add_worktime_project.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ formset.media }}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-12 col-md-8 col-lg-6 form-group">
      <h2>Add Worktime</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'projects:add_worktime_project' project.pk %}" id="worktimeForm">

        {{ formset.management_form }}
        {% csrf_token %}
        {% for form in formset %}
        <h4>Worktime</h4>
        <div class="worktime-form">
          {% bootstrap_form form %}
          <br>
        </div>
        {% endfor %}
        <button id="add-form" type="button" class="btn btn-outline-primary mb-4">Add another</button>
        <br>
        <p>
          <button type="submit" class="btn btn-primary btn-large">Save</button>
          <a href="javascript:window.history.back()"><button type="button" class="btn btn-default btn-large">Cancel</button></a>
        </p>
        <p style="line-height:1.6em;"></p>
        <p style="margin-left:0px; font-size:0.9em">Do you want to add a new <strong><a href="{% url 'team:add_task_user' user.pk %}"> Task</a></strong>?</p>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script>
let worktimeForm = document.querySelectorAll(".worktime-form")
let container = document.querySelector("#worktimeForm")
let addButton = document.querySelector("#add-form")
let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

let formNum = worktimeForm.length-1
addButton.addEventListener('click', addForm)

function addForm(e){
    e.preventDefault()

    let newForm = worktimeForm[0].cloneNode(true)
    let formRegex = RegExp(`form-(\\d){1}-`,'g')

    formNum++
    newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
    container.insertBefore(newForm, addButton)

    totalForms.setAttribute('value', `${formNum+1}`)
}



</script>
{% endblock %}

projects/templates/projects/edit_project.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="container">
  <div class="row align-items-center justify-content-around mt-4">
    <div class="col-auto">
      <h2>Edit Project</h2>
      <p style="line-height:1.6em;"></p>
      <form method="POST" action="{% url 'projects:edit_project' project.pk %}" id="projectForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary btn-large">Save</button>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

projects/templates/projects/project_categories_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% load bootstrap4 %}
{% bootstrap_javascript jquery='full' %}

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
      <li class="breadcrumb-item">Project Categories</li>
    </ol>
  </nav>

  <div class="row justify-content-center">
    <div class="col-12 col-md-10 m-0 p-0">
      <!-- Projects area -->
      <p style="line-height:1.6em;"></p>
      <h4 class="table-header">Project Categories<a href="{% url 'projects:add_project_category' %}" class="btn btn-light btn-sm" role="button"> +</a></h4>
      {% if projectcategory_list %}
      <table style="width:100%" class="table table-hover table-sm justify-content-md-center">
        <thead class="thead-dark">
          <tr>
            <th class="align-middle" scope="col">Number</th>
            <th class="align-middle" scope="col">Name</th>
            <th class="align-middle text-center" scope="col">No. of Projects</th>
            <th class="align-middle text-center" scope="col">Open tasks</th>
          </tr>
        </thead>
        {% for p in projectcategory_list %}
        <tr class='clickable-row' data-href="{% url 'projects:project_category' p.projectcategory_number %}">
          <td class="align-middle">{{ p.projectcategory_number }}</td>
          <td class="align-middle">{{ p.projectcategory_name }}</td>
          <td class="align-middle text-center">{{ p.category_projects.count }}</td>
          {% if p.num_tasks %}
          <td class="align-middle text-center">{{ p.num_tasks }}</td>
          {% else %}
          <td class="align-middle text-center">0</td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>
      {% else %}
      <p>No project categories are available.</p>
      <a href="{% url 'projects:add_project_category' %}" class="btn btn-light btn-sm" role="button">Add a project category +</a>
      {% endif %}
    </div>
  </div>
<br>
  <div class="row justify-content-center">
    <div class="col-auto">
      <div class="card busiest_projects">
        <div class="chart-container">
          <h6 class="title white">Busiest Projects</h6>
          {% if project_hours_2weeks %}
          <canvas id="busiest_projects"></canvas>
          {% else %}
          <p class="message white">No hours have been logged <span><br>in the past two weeks.</span></p>
          {% if user %}
          <br>
          <p><a href="{% url 'team:add_worktime_user' user.pk %}" class="btn btn-info btn-sm">Log hours</a></p>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-auto">
      <div class="card busiest_project_categories">
        <div class="chart-container">
          <h6 class="title white">Activity per Project Category<span><br><h6>past 2 weeks</h6></span></h6>
          {% if project_hours_2weeks %}
          <canvas id="busiest_project_categories"></canvas>
          {% else %}
          <p class="message white">No hours have been logged <span><br>in the past two weeks.</span></p>
          {% if user %}
          <br>
          <p><a href="{% url 'team:add_worktime_user' user.pk %}" class="btn btn-info btn-sm">Log hours</a></p>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}
<!-- end of body block -->

{% block scripts %}
  <script type="text/javascript">
    $(document).ready(function($) {
      $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
      });
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>
{% include "projects/busiest_projects.html" %}
{% include "projects/busiest_project_categories.html" %}

{% endblock scripts %}