ProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index.as_view(), name='index'),
    path('search/', views.projectsearch.as_view(), name='projectsearch'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('add_task_index/<int:pk>/', views.add_task_index.as_view(), name='add_task_index'),
    # URL patterns for charts
    path('user_tasks_chart/', views.user_tasks_chart, name='user_tasks_chart'),
    path('team_tasks_category/', views.team_tasks_category, name='team_tasks_category'),
    # This will include all the login-registtration etc. URL patterns:
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls',namespace="projects")),
    path('subcontractors/', include('subcontractors.urls',namespace="subcontractors")),
    path('team/', include('team.urls',namespace="team")),
    path('reports/', include('reports.urls',namespace="reports")),
    path('api/search_autocomplete/', views.search_autocomplete, name='search_autocomplete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup.as_view(), name='signup'),
    path('edit_user/<int:pk>/', views.edit_user.as_view(), name='edit_user'),
    path('delete_user/<int:pk>/', views.delete_user.as_view(), name='delete_user'),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'
urlpatterns = [
    path('', views.project_categories_list.as_view(), name='project_categories_list'),
    path('<int:projectcategory_number>/', views.project_category.as_view(), name='project_category'),
    path('projects/<int:pk>/', views.project_detail.as_view(), name='project_detail'),
    path('add_project/<int:pk>/', views.add_project.as_view(), name='add_project'),
    path('add_projectcategory/', views.add_project_category.as_view(), name='add_project_category'),
    path('edit_project/<int:pk>/', views.edit_project.as_view(), name='edit_project'),
    path('add_job_project/<int:pk>/', views.add_job_project.as_view(), name='add_job_project'),
    path('add_task_project/<int:pk>/', views.add_task_project.as_view(), name='add_task_project'),
    path('join_project/<int:pk>/', views.join_project.as_view(), name='join_project'),
    path('leave_project/<int:pk>/', views.leave_project.as_view(), name='leave_project'),
    path('project_task_history/<int:pk>/', views.project_task_history.as_view(), name='project_task_history'),
    path('busiest_projects/', views.busiest_projects, name='busiest_projects'),
    path('busiest_project_categories/', views.busiest_project_categories, name='busiest_project_categories'),
    path('project_hours_graph/<int:pk>/', views.project_hours_graph, name='project_hours_graph'),
    path('add_worktime_project/<int:pk>/', views.add_worktime_project, name='add_worktime_project'),
    path('add_worktime_modal/<int:pk>/', views.add_worktime_modal, name='add_worktime_modal'),
]

reports/urls.py
from django.urls import path
from reports import views

app_name = 'reports'
urlpatterns = [
    path('', views.reports_list.as_view(), name='reports_list'),
    path('add_report', views.add_report, name='add_report'),
    path('edit_report/<int:pk>/', views.edit_report, name='edit_report'),
    path('delete_report/<int:pk>/', views.delete_report.as_view(), name='delete_report'),
]

subcontractors/urls.py
from django.urls import path
from subcontractors import views

app_name = 'subcontractors'
urlpatterns = [
    path('contacts/', views.contact_list.as_view(), name='contact_list'),
    path('add_jobcategory/', views.add_jobcategory.as_view(), name='add_jobcategory'),
    path('add_contact/', views.add_contact.as_view(), name='add_contact'),
    path('edit_contact/<int:pk>/', views.edit_contact.as_view(), name='edit_contact'),
    path('delete_contact/<int:pk>/', views.delete_contact.as_view(), name='delete_contact'),
]

team/urls.py
from django.urls import path
from team import views

app_name = 'team'
urlpatterns = [
    path('', views.users_list.as_view(), name='users_list'),
    path('<int:pk>/', views.user_detail.as_view(), name='user_detail'),
    path('add_task_user/<int:pk>/', views.add_task_user.as_view(), name='add_task_user'),
    path('update_task_status/<int:pk>/', views.update_task_status, name='update_task_status'),
    path('edit_task_user/<int:pk>/', views.edit_task_user.as_view(), name='edit_task_user'),
    path('tasks/<int:pk>/', views.task_detail.as_view(), name='task_detail'),
    path('delete_task_user/<int:pk>/', views.delete_task_user.as_view(), name='delete_task_user'),
    path('worktime_list_user/<int:pk>/', views.worktime_list_user.as_view(), name='worktime_list_user'),
    path('worktime_history_user/<int:pk>/', views.worktime_history_user.as_view(), name='worktime_history_user'),
    path('add_worktime_user/<int:pk>/', views.add_worktime_user, name='add_worktime_user'),
    path('edit_worktime_user/<int:pk>/', views.edit_worktime_user.as_view(), name='edit_worktime_user'),
    path('delete_worktime_user/<int:pk>/', views.delete_worktime_user.as_view(), name='delete_worktime_user'),
    path('user_task_history/<int:pk>/', views.user_task_history.as_view(), name='user_task_history'),
    path('team_activity/', views.team_activity.as_view(), name='team_activity'),
    path('user_hours_graph/<int:pk>/', views.user_hours_graph, name='user_hours_graph'),
    path('add_worktime_task/<int:pk>/', views.add_worktime_task, name='add_worktime_task'),
]

templates/add_task_index.html
{% load bootstrap4 %}

{% block body %}

{% bootstrap_javascript jquery='full' %}
{{ form.media }}

<div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content col">
      <div class="modal-header">
        <h5 class="modal-title"">Add a Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class="col">
              <form method="POST" action="{% url 'add_task_index' user.id %}" id="taskForm">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% if form_error %}
                $(#addTaskModal).modal("show");
                {% endif %}
                {% buttons %}
                <button type="submit" class="btn btn-primary btn-large">Add</button>
                {% endbuttons %}
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% url 'index' as start %}
{% url 'projects:project_categories_list' as projects %}
{% url 'subcontractors:contact_list' as subcontractors %}
{% url 'team:users_list' as team %}
{% url 'reports:reports_list' as reports %}
{% url 'login' as login %}
{% load static %}

{% bootstrap_javascript jquery='full' %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" type="image/png" href="{% static '/css/img/favicon.ico' %}"/>
  <title>follo</title>
  {% include "css_links.html" %}
</head>

<body>
  <!-- Sidebar -->
  <div class="sideBar">
    <!-- Logo -->
    <div id="logo">
      <a href="{% url 'index' %}">
        <img id="logo" src="{% static '/css/img/Logo.svg' %}" alt="logo" />
      </a>
    </div>
    <!-- end of Logo -->
    <nav>
      <a class="nav-link {% if request.path == start %} active {% elif '/search/' in request.path %} active {% endif %}" href="{% url 'index' %}">
        <i class="fas fa-home"></i>
        Home
      </a>
      <a class="nav-link {% if '/projects/' in request.path %} active {% endif %}" href="{% url 'projects:project_categories_list' %}">
        <i class="fas fa-city"></i>
        Projects
      </a>
      <a class="nav-link {% if '/team/' in request.path %} active {% elif '/accounts/' in request.path %} active {% endif %}" href="{% url 'team:users_list' %}">
        <i class="fas fa-user-friends"></i>
        Team
      </a>
      <a class="nav-link {% if '/subcontractors/' in request.path %} active {% endif %}" href="{% url 'subcontractors:contact_list' %}">
        <i class="fas fa-address-book"></i>
        Agenda
      </a>
      <a class="nav-link {% if '/reports/' in request.path %} active {% endif %}" href="{% url 'reports:reports_list' %}">
        <i class="fas fa-book"></i>
        Reports
      </a>
      </nav>
  </div>
  <!-- End of Sidebar -->

  <!-- Navbar -->
  <header>
    <div class="nav-tools">
      {% if user.is_authenticated %}
      <!-- search bar -->
      <div class="searchBar">
        <form action="{% url 'projectsearch' %}" method="get" accept-charset="utf-8">
          <button type="submit">
            <i class="fas fa-search"></i>
          </button>
          <input type="text" id='searchInput' name="q" placeholder="Search">
        </form>
      </div>
      <!-- end of search bar -->
      <!-- initial in circle w/ dropdown -->
      <div class="dropdown">
        <span class="nav-link pl-0" id="dropdownMenuButton2" data-toggle="dropdown">
          <div class="user-circle" style="background-color:rgba{{ user.profile.user_color }};">
            <span class="black initials" style="cursor:default">
              {{ user.username|first|title }}
            </span>
          </div>
        </span>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton2" id="dropdownMenu">
          <a class="dropdown-item" style="color:grey">{{ user.username }}</a>
          <a class="dropdown-item" href="{% url 'team:user_detail' user.pk %}">Profile</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
        </div>
      </div>
    <!-- end of initial in circle w/ dropdown -->
    {% else %}
    <div class="user-area">
      <a href="{% url 'login' %}" class="nav-link login" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Login
      </a>
    </div>
    {% endif %}
  </div>
</header>
<!-- End of Navbar -->

<!-- Main content -->
<div id="page-content-wrapper">
  <div class="content">
    {% block body %}
    {% endblock %}
  </div>
</div>
<!-- end of Main content -->
<!-- Scripts -->

{% include "scripts_links.html" %}
{% block scripts %}{% endblock %}

</body>

</html>

templates/css_links.html
<!DOCTYPE html>
{% load static %}
<!-- bootstrap css -->
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<!-- chart css -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
<!-- jquery css -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!-- custom css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_javascript jquery='full' %}
{% block body %}



{% if user.is_authenticated %}
<!-- Add Task Modal -->
{% include "add_task_index.html" %}
<!-- end of Add Task Modal -->

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    </ol>
  </nav>


  <div class="row justify-content-around align-items-start">
    <div class="col-lg-8 columnOne">
      <div class="row justify-content-around">
        <div class="col-auto">
            <div class="card task-chart">
              <div class="chart-container">
                <h6 class="title white">Tasks<span><button class="add_task_popup white"
                  data-toggle="modal" data-target="#addTaskModal"> +</button></span></h6>
                <canvas id="task-chart" width="180" height="180"></canvas>
              </div>
          </div>
        </div>
        <div class="col-sm ml-0 pl-0">
          <div class="row justify-content-center align-items-center">
            <div class="col-auto h-25 m-0 p-0">
              <div class="card todo report-status">
                <div class="chart-container">
                  {% if weekly_report %}
                  <a href="{% url 'reports:edit_report' weekly_report.0.pk %}"><i type="submit black" class="far fa-check-circle"></i></a>
                  <p class="todoTitle black">Weekly Report</p>
                  <p class="todoText black">Status:<br>Submitted</p>
                  {% else %}
                  <a href="{% url 'reports:add_report' %}"><i type="submit black" class="far fa-times-circle"></i></a>
                  <p class="todoTitle black">Weekly Report</p>
                  <p class="todoText black">Submit by:<br>{{ report_day|date:"D d M" }}</p>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="col-auto h-25 m-0 p-0">
              <div class="card todo work-hours">
                <div class="chart-container">
                  {% if daily_worktime|length %}
                  <a href="{% url 'team:add_worktime_user' user.id %}"><i type="submit" class="black far fa-check-circle"></i></a>
                  <p class="black todoTitle">Work hours</p>
                  <p style="line-height:0.25em;"><br></p>
                  <p class="black todoText">Submit: Daily</p>
                  <p class="black todoText">Daily total: {{ total_daily_worktime.worktime_hour__sum }}</p>
                  {% else %}
                  <a href="{% url 'team:add_worktime_user' user.id %}"><i class="black far fa-times-circle"></i></a>
                  <p class="black todoTitle">Work hours</p>
                  <p style="line-height:0.15em;"><br></p>
                  <p class="black todoText">Submit:<br>daily</p>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="w-100"></div>
        <div class="col-12 mr-0 pl-3 pr-3 pt-2 pb-2">
          <section class="middle">
              <div class="card recent-activity">
                <div class="chart-container">
                  <div class="groupHeader">
                    <h6 class="white">Recent Team Activity<span><a href="{% url 'team:team_activity' %}"><i class="white far fa-calendar-alt"></i></a></span></h6>
                  </div>
                  {% if recently_completed_tasks %}
                  {% for t in recently_completed_tasks %}
                  <p class="white"><a class="white" href="{% url 'team:user_detail' t.task_asignee.pk %}">@{{ t.task_owner }}</a>
                    {% if t.task_completion_date %}
                    completed
                    <a class="white" href="{% url 'team:task_detail' t.pk %}">"{{ t.task_description }}"</a>
                    <span class="white">- {{ t.task_completion_date }}</span></p>
                    {% else %}
                    created
                    <a class="white" href="{% url 'team:task_detail' t.pk %}">"{{ t.task_description }}"</a>
                    <span class="white">- {{ t.task_creation_date }}</span></p>
                    {% endif %}
                    {% endfor %}
                  {% else %}
                  <p class="white">No recent activity.</p>
                  {% endif %}
                </div>
              </div>
          </section>
        </div>
      </div>
    </div>
    <div class="col-lg-4 columnTwo">
      <div class="row justify-content-center align-items-start">
        <div class="col-auto mb-2">
          <div class="card projects-timeline">
            <div class="chart-container">
              <h6 class="white">Project Deadlines</h6>
              {% if projects_user %}
              <div class="timeline">
                <ul>
                  <li class="today white">
                    <div class="timeline-content">
                      <p class="title white">Today</p>
                    </div>
                    <div class="timeline-time">
                      <p class="subtitle white">
                        {% now 'N j, Y' %}
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
              {% if approaching_projects %}
              {% for a in approaching_projects|slice:":3" %}
              <!-- timeline code start -->
              <div class="timeline">
                <ul>
                  <li class="future">
                    <div class="timeline-content">
                      <p class="title"><a class="white" href="{% url 'projects:project_detail' a.pk %}">{{ a }}</a></p>
                    </div>
                    <div class="timeline-time">
                      <p class="white subtitle">{{ a.project_delivery_date }}</p>
                    </div>
                  </li>
                </ul>
              </div>
              <!-- timeline code end -->
              {% endfor %}
              {% endif %}
              {% else %}
              <p class="white">You haven't joined any projects yet.
              <br>
              <br>
              <a href="{% url 'projects:project_categories_list' %}" class="btn btn-info btn-sm">Join a project</a>
              </p>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col-auto mb-2">
          <div class="card team-activity">
            <div class="chart-container">
              <h6 class="title white">Team Tasks per Category</h6>
              {% if pending_tasks %}
              <canvas id="team-activity" width="200" height="200"></canvas>
              {% else %}
              <p class="white">No open tasks.
                <br>
                <br>
                <a data-toggle="modal" data-target="#addTaskModal" class="btn btn-info btn-sm">Add a task</a>
              </p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="w-100"></div>
    <div class="col-12 m-2 pl-4 pr-4">
      <section class="bottom">
          <!-- Projects area -->
          <h5 class="table-header">My Projects</h5>
          {% if projects_user %}
          <table style="width:100%" class="table table-hover justify-content-md-center">
            <thead>
              <tr>
                <th class="align-middle" scope="col">Number</th>
                <th class="align-middle" scope="col">Name</th>
                <th class="align-middle" scope="col">Category</th>
                <th class="align-middle text-center" scope="col">Open tasks</th>
                <th class="align-middle" scope="col">Stage</th>
                <th class="align-middle" scope="col">Delivery date</th>
              </tr>
            </thead>
            {% for p in projects_user %}
            <tr class='clickable-row' data-href="{% url 'projects:project_detail' p.pk %}">
              <td class="align-middle">{{ p.project_number }}</td>
              <td class="align-middle">{{ p.project_name }}</td>
              <td class="align-middle">{{ p.project_category.projectcategory_name }}</td>
              <td class="align-middle text-center">{% if p.project_tasks.task_status == 'Pending' %}{{ p.project_tasks|length }}{% else %}None{% endif %}</td>
              <td class="align-middle">{{ p.project_stage }}</td>
              <td class="align-middle">{{ p.project_delivery_date }}</td>
            </tr>
            {% endfor %}
          </table>
          {% else %}
          <p>You have joined any projects yet! Join one <a href="{% url 'projects:project_categories_list' %}">here</a>.</p>
          {% endif %}
          <!-- End of Projects area -->
          <br>
          <!-- Tasks area -->
          <div class="w-100"></div>
            <h5 class="table-header">My Tasks
              <button class="black add_task_popup" data-toggle="modal" data-target="#addTaskModal"> +</button>
            </h5>
            {% if pending_tasks %}
            <table id="Tasks" style="width:100%" class="table table-hover justify-content-md-center">
              <thead>
                <tr>
                  <th class="align-middle" scope="col">Project</th>
                  <th class="align-middle" scope="col">Description</th>
                  <th class="align-middle" scope="col">Person</th>
                  <th class="align-middle" scope="col">Deadline</th>
                  <th class="align-middle text-center" scope="col">Mark as complete</th>
                  <th class="align-middle text-center" scope="col">Edit</th>
                  <th class="align-middle text-center" scope="col">Delete</th>
                </tr>
              </thead>
              {% if user_tasks %}
              {% for t in user_tasks %}
              {% if t.task_status == 'Pending' %}
              {% if t.is_past_due %}
              <tr style="background-color:#f8ddda">
              {% elif t.is_close_due %}
              <tr style="background-color:#fff4e1">
              {% else %}
              <tr style="background-color:#e4ede4">
              {% endif %}
              <td class="align-middle">{{ t.task_project }}</td>
              <td class="align-middle"><a href="{% url 'team:task_detail' t.pk %}"><p class="text-description">{{ t.task_description }}</p></a></td>
              <td class="align-middle">{{ t.task_asignee }}</td>
              <td class="align-middle"> {{ t.task_due_date }}</td>
              <td class="align-middle text-center task-update">
              <form action="{% url 'update_task_status' t.id %}"  method="post">
                {% csrf_token %}
                <button type="submit" name="button">
                  <a href="#">
                    <i type="submit" class="fas fa-check"></i>
                  </a>
                </button>
              </form>
              </td>
              <td class="align-middle text-center">
                <a href="{% url 'team:edit_task_user' t.pk %}" class="btn btn-sm" role="button"><i class="far fa-edit"></i></a>
              </td>
              <td class="align-middle text-center">
                <a href="{% url 'team:delete_task_user' t.pk %}" class="btn btn-sm">
                  <i class="far fa-trash-alt"></i>
                </a>
              </td>
              </tr>
              {% endif %}
              {% endfor %}
              {% endif %}
            </table>
            {% else %}
              <p>No tasks assigned yet.</p>
          {% endif %}
        </section>
      </div>
    </div>
  </div>


<!-- End of task area -->
<!-- end of user having signed-in -->
{% else %}
<!-- if user isn't signed in -->
<div class="row justify-content-around align-items-start">
  <div class="col-10 col-md-8 col-lg-6 mt-3">
    <h2>Welcome to follo!</h2>
    <p>Organize, manage and follow your projects easily. Please <strong><a href="{% url 'login' %}">login</a></strong> or <strong><a href="{% url 'accounts:signup' %}">sign up</a></strong> to start.</p>
  </div>
</div>
{% endif %}
<!-- end of main content div -->

{% endblock body %}
<!-- end of body block -->


<!-- Scripts go below -->
{% block scripts %}
<script type="text/javascript">
  $("#task-chart").click(function() {
    $('html,body').animate({
      scrollTop: $("#Tasks").offset().top},
      800);
    });

    $(document).ready(function($) {
      $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
      });
    });

    $(".todo").click(function() {
      window.location = $(this).find("a").attr("href");
      return false;
    });

  </script>
  <script src="http://vast-engineering.github.io/jquery-popup-overlay/jquery.popupoverlay.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>
  {% include "users_task_chart.html" %}
  {% include "team_tasks_category.html" %}

  {% endblock scripts %}
  <!-- end of scripts -->

templates/scripts_links.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/ed5ee3f06a.js" crossorigin="anonymous"></script>
<!--Chart js and css-->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script src="{% static 'js/master.js' %}" type="text/javascript"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.js'></script>
<script>
  $( function() {
    $("#searchInput").autocomplete({
      source: "{% url 'search_autocomplete' %}",
      minLength: 3,
    });
  });
</script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js"></script>
<!-- Latest compiled and minified Locales -->
<script src="https://unpkg.com/bootstrap-table@1.18.1/dist/locale/bootstrap-table-zh-CN.min.js"></script>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 m-2 pl-4 pr-4">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">Search results for "{{ val }}"</li>
        </ol>
      </nav>

      <ul>
        {% for o in object_list %}
        {% if o.project_number  %}
        <li><a href="{% url 'projects:project_detail' o.pk %}" class="btn btn-light" role="button">{{ o.project_number }} - {{ o.project_name }}</a></li>
        {% elif o.task_description %}
        <li><a href="{% url 'team:task_detail' o.pk %}" class="btn btn-light" role="button">{{ o }}</a></li>
        {% elif o.subcontractor_name %}
        <li><a href="{% url 'subcontractors:subcontractor_detail' o.pk %}" class="btn btn-light" role="button">{{ o }}</a></li>
        {% endif %}
        {% empty %}
        <h5>Sorry, no results found!</h5>
        <p>Go to <a href="{% url 'index' %}">main page</a>.</p>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>


{% endblock %}